# Generated by Django 3.2.16 on 2023-12-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='completedOn',
            field=models.DateField(null=True),
        ),
    ]
